# Docker Compose configuration - LightRAG Services
# Note: version field is deprecated and not needed in newer Docker Compose

services:
  # Service chính chạy LightRAG API
  lightrag-api:
    # Build image từ Dockerfile trong thư mục docker/
    build:
      context: ..                 # Build context từ thư mục cha (root project)
      dockerfile: docker/Dockerfile
    
    # Mapping port: host:container
    ports:
      - "8000:8000"               # API sẽ accessible tại http://localhost:8000
    
    # Biến môi trường cho container
    environment:
      - PYTHONPATH=/app/src       # Đường dẫn Python modules
      - PYTHONUNBUFFERED=1        # Hiển thị logs real-time
      - DATA_PATH=/app/data/data.txt  # File dữ liệu chính
      # Neo4j connection settings
      - NEO4J_URI=bolt://neo4j:7687      # URI kết nối Neo4j (tên service trong docker)
      - NEO4J_USERNAME=neo4j              # Username Neo4j
      - NEO4J_PASSWORD=your_password      # Password Neo4j (nên đặt trong .env)
    
    # Mount volumes để chia sẻ dữ liệu giữa host và container
    volumes:
      # Mount thư mục data (read-only) - chứa file data.txt
      - ../data:/app/data:ro
      
      # Mount persistent storage cho RAG indexes và embeddings
      # Volume này sẽ được giữ lại khi restart container
      - lightrag_storage:/app/rag_storage
      
      # Mount file .env nếu tồn tại (chứa API keys)
      - ../.env:/app/.env:ro
      
      # Mount logs directory để xem logs từ host (optional)
      - ./logs:/app/logs
    
    # Restart policy: tự động restart trừ khi stop manual
    restart: unless-stopped
    
    # Health check để monitoring container health
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s               # Kiểm tra mỗi 30 giây
      timeout: 10s                # Timeout sau 10 giây
      retries: 3                  # Thử lại 3 lần nếu fail
      start_period: 60s           # Chờ 60s sau khi start mới bắt đầu check
    
    # Kết nối với network riêng
    networks:
      - lightrag_network
    
    # Dependencies - chờ Neo4j ready trước khi start
    depends_on:
      neo4j:
        condition: service_healthy

  # Service Neo4j - Graph Database cho Knowledge Graph
  neo4j:
    image: neo4j:5.15                     # Sử dụng Neo4j version 5.15
    container_name: lightrag_neo4j
    ports:
      - "7474:7474"                       # Neo4j Browser UI
      - "7687:7687"                       # Bolt protocol cho connections
    environment:
      # Authentication settings
      - NEO4J_AUTH=neo4j/your_password    # Username/Password
      # Performance settings
      - NEO4J_PLUGINS=["apoc"]            # APOC procedures (Advanced)
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      # Security settings
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
    volumes:
      # Persistent storage cho Neo4j data
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - lightrag_network
    restart: unless-stopped
    # Health check để đảm bảo Neo4j ready trước khi start LightRAG
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "your_password", "RETURN 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

# Persistent volumes để lưu trữ dữ liệu lâu dài
volumes:
  # Volume cho RAG storage (indexes, embeddings, cache)
  lightrag_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/rag_storage  # Lưu tại ./volumes/rag_storage trên host
  
  # Volumes cho Neo4j
  neo4j_data:
    driver: local
    driver_opts:
      type: none  
      o: bind
      device: ./volumes/neo4j_data   # Lưu Neo4j data tại ./volumes/neo4j_data
  
  neo4j_logs:
    driver: local
    driver_opts:
      type: none
      o: bind  
      device: ./volumes/neo4j_logs   # Lưu Neo4j logs tại ./volumes/neo4j_logs
  
  neo4j_import:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/neo4j_import # Thư mục import data vào Neo4j
  
  neo4j_plugins:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/neo4j_plugins # Neo4j plugins

# Network riêng cho các services có thể communicate
networks:
  lightrag_network:
    driver: bridge
    # Cấu hình subnet tùy chỉnh (optional)
    ipam:
      config:
        - subnet: 172.20.0.0/16
